services:
  create3-republisher:
    image: create3-republisher:latest
    restart: always
    env_file:
      - /etc/turtlebot4/docker/config/create3.env
    command: ros2 launch create3_republisher create3_republisher_launch.py robot_ns:=/ republisher_ns:=/create3_repub
    profiles:
      - create3
    volumes:
      - /etc/turtlebot4/docker/config:/opt/config
    networks:
      vlan:
        ipv4_address: 192.168.186.100

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: usb0
    ipam:
      config:
        - subnet: 192.168.186.0/24
          ip_range: 192.168.186.0/24
