services:
  create3-republisher:
    image: create3-republisher:latest
    restart: always
    env_file:
      - /etc/turtlebot4/docker/config/create3.env
    command: ros2 launch create3_republisher create3_republisher_launch.py robot_ns:=/create3 republisher_ns:=/
    profiles:
      - create3
    volumes:
      - /etc/turtlebot4/docker/config:/opt/config
    networks:
      vlan:
        ipv4_address: 192.168.186.100
      tbt4_container_bridge:
        ipv4_address: 192.168.187.100

networks:
  # Give the docker container a public-facing IP address on the usb0 network to allow it to
  # communicate with the Create3 hardware.
  vlan:
    driver: macvlan
    driver_opts:
      parent: usb0
    ipam:
      config:
        - subnet: 192.168.186.0/24
          ip_range: 192.168.186.0/24

  # Define a second interface for the container to allow it to talk with the host without
  # risking spilling over into the 192.168.186.0/24 subnet
  tbt4_container_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.187.0/24
          ip_range: 192.168.187.0/24
